### ISSUE TITLE
Prévoir un fichier de mise à jour de la bdd

### ISSUE THREAD

**Issue by GithubWingi** [LucasMartinn/ProjetSyntheseGRP4#4]
Me communiquer le chemin/nom du fichier pour exécution à chaque mise à jour du site.
A voir si le mécanisme sera systématique ou conditionnel/configuré

**Comment by daveurandom** [comment]
J'ai modifié le fichier /deploy.php pour qu'il modifie la base de donnée si il y a déjà des tables. Il peut être exécuté à chaque mise à jour du site.
